# "OrdererOrgs" - Definition of organizations managing orderer nodes
OrdererOrgs:
  - Name: OrdererOrg
    Domain: cvverification.com
    # Specs is an array of Spec entries.  Each Spec entry consists of two fields : Hostname and CommonName
    Specs:
      - Hostname: orderer
# "PeerOrgs" - Definition of organizations managing peer nodes
PeerOrgs:
  - Name: Org1CVVerification
    Domain: org1.cvverification.com
    # Allows for the definition of 1 or more hosts that are created sequentially
    # from a template. By default, this looks like "peer%d" from 0 to Count-1.
    # You may override the number of nodes (Count), the starting index (Start)
    # or the template used to construct the name (Hostname).
    Template:
      Count: 2
    Users:
      # Count: The number of user accounts _in addition_ to Admin
      Count: 2

  - Name: Org2CVVerification
    Domain: org2.cvverification.com
    # Allows for the definition of 1 or more hosts that are created sequentially
    # from a template. By default, this looks like "peer%d" from 0 to Count-1.
    # You may override the number of nodes (Count), the starting index (Start)
    # or the template used to construct the name (Hostname).
    Template:
      Count: 1
    Users:
      # Count: The number of user accounts _in addition_ to Admin
      Count: 1

  - Name: Org3CVVerification
    Domain: org3.cvverification.com
    # Allows for the definition of 1 or more hosts that are created sequentially
    # from a template. By default, this looks like "peer%d" from 0 to Count-1.
    # You may override the number of nodes (Count), the starting index (Start)
    # or the template used to construct the name (Hostname).
    Template:
      Count: 1
    Users:
      # Count: The number of user accounts _in addition_ to Admin
      Count: 1