[[constraint]]
name = "github.com/hyperledger/fabric"
branch = "release-1.4"

[[override]]
name = "github.com/fsouza/go-dockerclient"
version = "=1.2.1"

[prune]
  go-tests = true
  unused-packages = true
